### ISSUE TITLE
Crash on 1.19.3

### ISSUE THREAD

**Issue by darthvader45** [magicus/ModSettings#16]
Got a similar error to #15 , though it's a NoSuchMethodError:

https://paste.ee/p/vvEGz

Only running AzureLib v1.0.6, EMI 0.6.6 for 1.19.3, EnergizedPower 1.4.3 for 1.19.3, FabricAPI 0.75.1, FallingTree 3.11.2, From Another World 1.0.1, Geckolib 4.0.4, Happiness (Is A Warm Gun) 1.3.3, and Journeymap 5.9.4, as well as ModSettings.

**Comment by magicus** [comment]
Thanks for the report. I could have sworn I tested that the 1.19 release worked on 1.19.3, but it fails immediately for me too when I test it now.

**Comment by magicus** [comment]
I have now released a proper working version for 1.19.3.

**Comment by darthvader45** [comment]
Thanks.  Wondered what was wrong.
